#let entries = (
  (key: "graph", short: $G=(V,E)$, long: "city graph", description: [The finite undirected graph whose vertices represent locations or movement connectors and whose edges represent roads.]),
  (key: "vertex", short: $v$, long: "vertex", description: [A graph location; in EpiGraph it may be a population-bearing facility or a zero-population connector.]),
  (key: "edge", short: $e$, long: "edge", description: [A road segment joining two vertices.]),
  (key: "sir", short: "SIR", long: "susceptible–infected–removed", description: [The compartment vocabulary used for count updates: susceptible, infected, recovered, and deceased.]),
  (key: "susceptible", short: $S$, long: "susceptible population", description: [People who have not yet been infected in the stated scenario.]),
  (key: "infected", short: $I$, long: "infected population", description: [Modeled currently infectious people at a location.]),
  (key: "recovered", short: $R$, long: "recovered population", description: [People removed from the infectious state through the model’s recovery transition.]),
  (key: "deceased", short: $D$, long: "deceased population", description: [People removed through the model’s mortality transition.]),
  (key: "hazard", short: $p$, long: "daily transmission probability", description: [A bounded scenario probability used in binomial infection trials.]),
  (key: "seed", short: $sigma$, long: "simulation seed", description: [An integer controlling deterministic pseudo-random event draws.]),
  (key: "degree", short: $deg(v)$, long: "degree centrality", description: [The number of graph edges incident to a vertex.]),
  (key: "betweenness", short: $C_B(v)$, long: "betweenness centrality", description: [The sum of fractions of shortest paths between pairs that pass through a vertex.]),
  (key: "shortest-path", short: $d(s,t)$, long: "shortest path", description: [The least total transformed edge cost between source and destination.]),
  (key: "min-cut", short: $(S,T)$, long: "minimum cut", description: [A partition of a flow network whose crossing edges have minimum total capacity.]),
  (key: "capacity", short: $c(e)$, long: "edge capacity", description: [A modeled road-class proxy used only by the max-flow/min-cut strategy.]),
  (key: "budget", short: $B$, long: "intervention budget", description: [Upper bounds on closed roads, quarantined nodes, and quarantined population.]),
  (key: "baseline", short: $C_0$, long: "baseline cumulative infections", description: [The final cumulative infection count with no algorithm-selected intervention.]),
  (key: "containment", short: $eta$, long: "containment rate", description: [The bounded relative reduction in final cumulative infections against the baseline.]),
  (key: "prior", short: $P(H)$, long: "prior probability", description: [The location-risk probability before current symptom evidence is incorporated.]),
  (key: "likelihood", short: $P(E|H)$, long: "likelihood", description: [The modeled probability of observed symptom evidence if the location is at risk.]),
  (key: "posterior", short: $P(H|E)$, long: "posterior probability", description: [The normalized Bayesian risk score after applying local evidence.]),
  (key: "false-positive", short: $P(E|not H)$, long: "false-positive likelihood", description: [The modeled probability of the evidence if the location is not at risk.]),
  (key: "fixture", short: "fixture", long: "offline road-graph fixture", description: [A versioned stored graph snapshot used for reproducible Demonstration Mode without a live map request.]),
  (key: "fairness", short: "fairness protocol", long: "fair comparison protocol", description: [Shared graph, outbreak parameters, initial infections, seed, duration, and budget across all five strategies.]),
  (key: "tie", short: "tie", long: "tie-aware winner status", description: [A comparison result with equal final infections and modeled deaths for more than one strategy.]),
  (key: "osm", short: "OSM", long: "OpenStreetMap", description: [The volunteered geographic-data source used only for bounded road geometry.]),
  (key: "overpass", short: "Overpass", long: "Overpass API", description: [A public query service used as the primary bounded OSM road-data route.]),
  (key: "ttl", short: "TTL", long: "time to live", description: [The in-memory cache duration for a normalized live road import.]),
  (key: "electron", short: "Electron", long: "Electron desktop shell", description: [The desktop runtime that launches the portable Windows application and local loopback server.]),
  (key: "projection", short: "projection", long: "scenario-model projection", description: [An output conditional on the stated synthetic inputs, not a real-world forecast.]),
)
