import { createDemonstrationController, DEMONSTRATION_PRESETS } from "@shared/demoPresets";
import { PRESENTER_NOTES } from "@shared/presentationTools";
import { ChevronLeft, ChevronRight, Compass, Loader2, Play, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import React from "react";

const readableWinner = (winner: string) => winner.replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());

export function DemonstrationMode({ activeIndex, isLoading, onLoad, onClose }: { activeIndex: number; isLoading: boolean; onLoad: (index: number) => void; onClose: () => void }) {
  const preset = DEMONSTRATION_PRESETS[activeIndex]!;
  const controls = createDemonstrationController(activeIndex, onLoad, onClose);
  return <section className="mt-5 overflow-hidden rounded-[1.45rem] border border-violet-300/30 bg-[radial-gradient(circle_at_82%_5%,rgba(168,85,247,.20),transparent_28%),linear-gradient(135deg,#16233b,#0a1526)] p-5 text-white shadow-[0_20px_55px_rgba(30,27,75,.22)] sm:p-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="max-w-3xl"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.17em] text-violet-200"><Sparkles className="h-3.5 w-3.5" /> Guided demonstration mode · Step {activeIndex + 1} of {DEMONSTRATION_PRESETS.length}</div><h2 className="mt-2 text-2xl font-bold tracking-tight">{preset.title}</h2><p className="mt-2 text-sm leading-6 text-slate-200">{preset.narrative}</p></div><Button variant="outline" onClick={controls.close} className="border-white/20 bg-white/5 text-white hover:bg-white/10 hover:text-white">Exit demo</Button></div>
    <div className="mt-5 grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-white/10 bg-slate-950/35 p-4"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-cyan-200">Why this scenario matters</p><p className="mt-2 text-sm font-semibold leading-6 text-white">{preset.teachingPoint}</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><DemoMetric label="Transmission" value={preset.parameters.transmissionRate.toFixed(2)} /><DemoMetric label="Recovery" value={preset.parameters.recoveryRate.toFixed(2)} /><DemoMetric label="Days" value={preset.parameters.days.toString()} /><DemoMetric label="Road budget" value={preset.budget.maxRoadClosures.toString()} /></div></div><div className="rounded-2xl border border-violet-200/20 bg-violet-400/10 p-4"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-violet-200">Verified teaching contrast</p><p className="mt-2 text-base font-bold text-white">Expected leader: {readableWinner(preset.winner)}</p><p className="mt-2 text-xs leading-5 text-slate-200">Bounded map: {preset.map.placeName}. The run stays fair: every strategy receives the same graph, starting location, seed, epidemic parameters, and budget.</p></div></div>
    <details className="mt-5 rounded-xl border border-white/10 bg-slate-950/25 px-4 py-3"><summary className="cursor-pointer text-xs font-bold text-cyan-100">Presenter notes for this demonstration</summary><ol className="mt-3 list-decimal space-y-1.5 pl-4 text-[11px] leading-5 text-slate-200">{PRESENTER_NOTES.map(note => <li key={note}>{note}</li>)}</ol></details>
    <div className="mt-5 flex flex-wrap items-center gap-2"><Button onClick={controls.loadCurrent} disabled={isLoading} className="rounded-xl bg-cyan-300 text-slate-950 hover:bg-cyan-200">{isLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Play className="mr-2 h-4 w-4" />}{isLoading ? "Loading real-street scenario…" : "Load and run this scenario"}</Button><Button onClick={controls.loadPrevious} disabled={isLoading} variant="outline" className="rounded-xl border-white/20 bg-white/5 text-white hover:bg-white/10 hover:text-white"><ChevronLeft className="mr-1 h-4 w-4" /> Previous</Button><Button onClick={controls.loadNext} disabled={isLoading} variant="outline" className="rounded-xl border-white/20 bg-white/5 text-white hover:bg-white/10 hover:text-white">Next <ChevronRight className="ml-1 h-4 w-4" /></Button><span className="ml-auto inline-flex items-center gap-1.5 text-[10px] text-slate-300"><Compass className="h-3.5 w-3.5 text-cyan-200" /> Reproducible real-road configurations</span></div>
  </section>;
}

function DemoMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/10 bg-white/[0.06] px-3 py-2"><p className="text-[9px] uppercase tracking-wider text-slate-300">{label}</p><p className="mt-0.5 text-sm font-bold text-white">{value}</p></div>; }
